/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripNewRouteImport } from './routes/trip.new'
import { Route as SharedShareTokenRouteImport } from './routes/shared.$shareToken'
import { Route as TripTripIdReviewRouteImport } from './routes/trip.$tripId.review'
import { Route as TripTripIdPlanRouteImport } from './routes/trip.$tripId.plan'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripNewRoute = TripNewRouteImport.update({
  id: '/trip/new',
  path: '/trip/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedShareTokenRoute = SharedShareTokenRouteImport.update({
  id: '/shared/$shareToken',
  path: '/shared/$shareToken',
  getParentRoute: () => rootRouteImport,
} as any)
const TripTripIdReviewRoute = TripTripIdReviewRouteImport.update({
  id: '/trip/$tripId/review',
  path: '/trip/$tripId/review',
  getParentRoute: () => rootRouteImport,
} as any)
const TripTripIdPlanRoute = TripTripIdPlanRouteImport.update({
  id: '/trip/$tripId/plan',
  path: '/trip/$tripId/plan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/shared/$shareToken': typeof SharedShareTokenRoute
  '/trip/new': typeof TripNewRoute
  '/trip/$tripId/plan': typeof TripTripIdPlanRoute
  '/trip/$tripId/review': typeof TripTripIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/shared/$shareToken': typeof SharedShareTokenRoute
  '/trip/new': typeof TripNewRoute
  '/trip/$tripId/plan': typeof TripTripIdPlanRoute
  '/trip/$tripId/review': typeof TripTripIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/shared/$shareToken': typeof SharedShareTokenRoute
  '/trip/new': typeof TripNewRoute
  '/trip/$tripId/plan': typeof TripTripIdPlanRoute
  '/trip/$tripId/review': typeof TripTripIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/shared/$shareToken'
    | '/trip/new'
    | '/trip/$tripId/plan'
    | '/trip/$tripId/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/shared/$shareToken'
    | '/trip/new'
    | '/trip/$tripId/plan'
    | '/trip/$tripId/review'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/shared/$shareToken'
    | '/trip/new'
    | '/trip/$tripId/plan'
    | '/trip/$tripId/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  SharedShareTokenRoute: typeof SharedShareTokenRoute
  TripNewRoute: typeof TripNewRoute
  TripTripIdPlanRoute: typeof TripTripIdPlanRoute
  TripTripIdReviewRoute: typeof TripTripIdReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/new': {
      id: '/trip/new'
      path: '/trip/new'
      fullPath: '/trip/new'
      preLoaderRoute: typeof TripNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$shareToken': {
      id: '/shared/$shareToken'
      path: '/shared/$shareToken'
      fullPath: '/shared/$shareToken'
      preLoaderRoute: typeof SharedShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/$tripId/review': {
      id: '/trip/$tripId/review'
      path: '/trip/$tripId/review'
      fullPath: '/trip/$tripId/review'
      preLoaderRoute: typeof TripTripIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/$tripId/plan': {
      id: '/trip/$tripId/plan'
      path: '/trip/$tripId/plan'
      fullPath: '/trip/$tripId/plan'
      preLoaderRoute: typeof TripTripIdPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  SharedShareTokenRoute: SharedShareTokenRoute,
  TripNewRoute: TripNewRoute,
  TripTripIdPlanRoute: TripTripIdPlanRoute,
  TripTripIdReviewRoute: TripTripIdReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
